import streamlit as st
import pandas as pd
import numpy as np
import joblib
import os
from pathlib import Path

st.set_page_config(
    page_title="AI Text Detection",
    page_icon="🤖",
    layout="wide",
    initial_sidebar_state="expanded"
)

st.markdown("""
<style>
    .main {
        padding-top: 2rem;
    }
    .stMetric {
        background-color: #f0f2f6;
        padding: 1rem;
        border-radius: 0.5rem;
    }
</style>
""", unsafe_allow_html=True)

@st.cache_resource
def load_models():
    try:
        model = joblib.load('models/best_model.pkl')
        preprocessing = joblib.load('models/preprocessing.pkl')
        return model, preprocessing
    except Exception as e:
        st.error(f"Error loading models: {e}")
        return None, None

def main():
    st.title("🤖 AI-Generated Text Detection")
    st.markdown("---")
    
    st.markdown("""
    ### Welcome to the AI Text Detection System
    
    This application uses machine learning to detect whether a given text was written by a human or generated by an AI model.
    
    **Navigate using the sidebar to:**
    - 📊 View EDA Dashboard
    - 🎯 Test the Model Demo
    - 📈 Check Model Evaluation
    - 🔍 Explore SHAP Interpretation
    - 📚 Read Documentation
    """)
    
    col1, col2, col3 = st.columns(3)
    
    with col1:
        st.metric("📁 Dataset", "DAIGT V2", "44,868 essays")
    
    with col2:
        st.metric("🎯 Model", "XGBoost", "Tuned")
    
    with col3:
        st.metric("✅ Target", "F1-Score", "Primary Metric")
    
    st.markdown("---")
    
    st.info("""
    💡 **How to use this app:**
    1. Start with the **EDA Dashboard** to explore the dataset
    2. Try the **Model Demo** to test predictions on custom text
    3. Review **Model Evaluation** for performance metrics
    4. Check **Interpretation** to understand key features
    5. Read **Documentation** for methodology details
    """)

if __name__ == "__main__":
    model, preprocessing = load_models()
    main()
