import streamlit as st
import joblib
import numpy as np
from scipy.sparse import hstack

st.set_page_config(page_title="Model Demo", page_icon="🎯", layout="wide")

st.title("🎯 Model Demo - Real-time Prediction")
st.markdown("---")

@st.cache_resource
def load_models():
    try:
        model = joblib.load('models/best_model.pkl')
        preprocessing = joblib.load('models/preprocessing.pkl')
        return model, preprocessing
    except Exception as e:
        st.error(f"Error loading models: {e}")
        return None, None

model, preprocessing = load_models()

if model and preprocessing:
    st.markdown("""
    Enter any text below and the model will predict whether it was written by a human or generated by an AI.
    """)
    
    user_text = st.text_area(
        "Enter text to analyze:",
        placeholder="Paste your text here...",
        height=200
    )
    
    if st.button("🔍 Analyze Text", use_container_width=True):
        if user_text.strip():
            try:
                tfidf = preprocessing['word_tfidf']
                char_tfidf = preprocessing['char_tfidf']
                
                X_tfidf = tfidf.transform([user_text])
                X_char = char_tfidf.transform([user_text])
                X_combined = hstack([X_tfidf, X_char])
                
                prediction = model.predict(X_combined)[0]
                probability = model.predict_proba(X_combined)[0]
                
                col1, col2 = st.columns(2)
                
                with col1:
                    if prediction == 0:
                        st.success("✅ **Human Written**", icon="✅")
                        confidence = probability[0] * 100
                    else:
                        st.error("🤖 **AI Generated**", icon="⚠️")
                        confidence = probability[1] * 100
                    
                    st.metric("Confidence", f"{confidence:.2f}%")
                
                with col2:
                    st.subheader("Prediction Probabilities")
                    prob_data = {
                        'Label': ['Human', 'AI'],
                        'Probability': [probability[0]*100, probability[1]*100]
                    }
                    
                    import plotly.express as px
                    fig = px.bar(prob_data, x='Label', y='Probability', 
                                color='Label', color_discrete_map={'Human': '#1f77b4', 'AI': '#ff7f0e'})
                    st.plotly_chart(fig, use_container_width=True)
                
                st.markdown("---")
                
                st.info("""
                **How the model works:**
                - Uses TF-IDF vectorization for word-level features
                - Combines character n-gram features for pattern detection
                - XGBoost classifier trained on DAIGT V2 dataset
                - Provides confidence scores for predictions
                """)
            
            except Exception as e:
                st.error(f"Error during prediction: {e}")
        else:
            st.warning("Please enter some text to analyze.")

else:
    st.error("Models not loaded. Please check the model files.")
